// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrp7pJSBGXG5QDm6IAETVf1AxbrNvv-Uw',
    appId: '1:901166465453:web:77b84ab6247c9a417e6124',
    messagingSenderId: '901166465453',
    projectId: 'space-fcde8',
    authDomain: 'space-fcde8.firebaseapp.com',
    storageBucket: 'space-fcde8.firebasestorage.app',
    measurementId: 'G-0VRB92W9MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt1PU2P7QwvDuhB9nkV8Ozj2C3P8B-rkY',
    appId: '1:901166465453:android:c2840eea6db8807d7e6124',
    messagingSenderId: '901166465453',
    projectId: 'space-fcde8',
    storageBucket: 'space-fcde8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLOOS7y0h_3jOYr72TTIGM_ZoW8KGGgHM',
    appId: '1:901166465453:ios:afd609da979dd4fb7e6124',
    messagingSenderId: '901166465453',
    projectId: 'space-fcde8',
    storageBucket: 'space-fcde8.firebasestorage.app',
    iosClientId: '901166465453-i9aasd54saoikcf2m48s26euobnumhhe.apps.googleusercontent.com',
    iosBundleId: 'com.onespace.onespace',
  );

}